Social Information and Cross-Situational Learning: Model
========================================================

```{r load packages}
library(bootstrap)
library(lme4)
library(ggplot2)
library(arm)
library(directlabels)
library(stringr)
library(plyr)
library(reshape2)
```

This is my first attempt to generate predicted results from Dan and Mike's model

```{r model}
rm(list=ls())
#### Parameter values
  model.gamma <- 1.609619
  model.lambda <- 0.1597503

# different sigma values to reflect the different amount of attention given to initial guess 
  model.sigma <- 1
  model.sigma <- 0.75
  model.sigma <- 0.5653685
  model.sigma <- 0.25

### Build dat data frame

  Int <- 1
  IntConds <- 1
  NumPic <- 4
  PicConds <- 4
  p_s <- NULL
  p_o <- NULL
  dat <- data.frame(Int, IntConds, NumPic, PicConds)

### Get values without for loop (this is the model)

    sn <- model.gamma*model.sigma*(dat$Int+1)^-model.lambda;
    on <- model.gamma*((1-model.sigma)/(dat$NumPic-1))*(dat$Int+1)^-model.lambda;
    wn <- on/4;

# probability correct on same trials (created if statement to set ceiling value for p_0 at 1)
   if(sn <= 1) {
     p_s[1] <- 
      mean(rbinom(100000,1,sn + (1-sn)/dat$NumPic))
     } else {
      p_s[1] <- 
      mean(rbinom(100000,1,1))
     }
# probability correct on switch trials     
    p_o[1] <- 
      mean(rbinom(100000,1,on + (1-on)/dat$NumPic))
# probability correct on new trials    
    p_w[1] <- 
      mean(rbinom(100000,1,(1-wn)/dat$NumPic) - wn)

# store values for plotting
ms.sig.25 <- c(p_s, p_o) # attention evenly allocated across all objects
ms.sig.56 <- c(p_s, p_o) # parameter from Dan's model
ms.sig.65 <- c(p_s, p_o) # more attention to target of eye gaze
ms.sig.75 <-c(p_s, p_o) # more attention to target of eye gaze
ms.sig.1 <- c(p_s, p_o) # all attention to target of eye gaze and no tracking of other objects
```

Now that we have our predicted values stored as vectors, we need to combine them into a data frame for plotting.

```{r df for plotting}
# create data frame for plotting 
p.cor <- c(ms.sig.25[1], ms.sig.56[1], ms.sig.75[1], ms.sig.1[1])
conditions <- c("Parallel Accumulator", "No Social Integrated", "Weak Social Integrated", "Strong Social Integrated")
trialType <- c("Same", "Same", "Same", "Same")
model.preds <- data.frame(p.cor, conditions, trialType, experiment)
str(model.preds)

# create data frame for switch trials predictions
p.cor <-  c(ms.sig.25[2], ms.sig.56[2], ms.sig.75[2], ms.sig.1[2])
trialType <- c("Switch", "Switch", "Switch", "Switch")
model.preds2 <- data.frame(p.cor, conditions, trialType, experiment)
str(model.preds2)

df.plotting <- rbind(model.preds, model.preds2)
str(df.plotting)
# order the factor levels of condition (strength of sigma/social cue)
df.plotting$conditions <- factor(df.plotting$conditions, levels=c("Parallel Accumulator", "No Social Integrated", "Weak Social Integrated", "Strong Social Integrated"), ordered=T)

df.plotting
```

Now we plot the predicted mean correct responses on the task.

```{r plot predicted mean correct}

q <- ggplot(df.plotting, aes(x=conditions, y=p.cor, color=trialType, size=1.5)) +
  geom_point(aes(size = 1.3)) +
  guides(size=FALSE) +
  geom_hline(yintercept=0.25, linetype="dashed")  +
  #geom_line(aes(y=correct,colour=trialType),data=newdat, lty=1) +
  xlab("Strength of Social Cue") +
  scale_y_continuous(limits = c(0,1),breaks=c(0,.25,.5,.75,1),
                     name = "Predicted Proportion Correct") +
  theme_bw(base_size=16) + 
 # scale_color_manual(values=c("dark gray","#808080","#333333","#626262" )) +
  geom_line(aes(group=trialType,y=p.cor),lty=1,size=1.3) +
  theme(axis.title.y=element_text(vjust=0.1)) +
  theme(axis.title.x=element_text(vjust=-0.5)) +
  scale_color_discrete(name="Trial Type") +
  theme(legend.position=c(.9, .6))
             
             
# scale_color_grey(start=.2,end=.5)

```


```{r dan's_model}
################# Start of Dan's code ################

for (n in 1:dat$PicConds) # different number of referents 
  for (i in 1:dat$IntConds) {
    
    #parallel
    #model.sigma <- 1/(dat$NumPic[n]);
    
#     sn <- model.gamma*model.sigma*(dat$Int[i]+1)^-model.lambda;
#     on <- model.gamma*((1-model.sigma)/(dat$NumPic[n]-1))*(dat$Int[i]+1)^-model.lambda;
#     wn <- on/4;
    
    sn <- model.gamma*model.sigma*(dat$Int[i]+1)^-model.lambda;
    on <- model.gamma*((1-model.sigma)/(dat$NumPic[n]-1))*(dat$Int[i]+1)^-model.lambda;
    wn <- on/4;
    
#     
#     sn <- c_s[((i-1)*dat$IntConds)+n]
#     on <- c_o[((i-1)*dat$IntConds)+n]
#     wn <-c_w[((i-1)*dat$IntConds)+n]     

    p_s[((i-1)*dat$IntConds)+n] <- 
      mean(rbinom(100000,1,sn + (1-sn)/dat$NumPic[n]))
    
    p_o[((i-1)*dat$IntConds)+n] <- 
      mean(rbinom(100000,1,on + (1-on)/dat$NumPic[n]))
    
    p_w[((i-1)*dat$IntConds)+n] <- 
      mean(rbinom(100000,1,(1-wn)/dat$NumPic[n]) - wn)
    
#     p_s[((i-1)*dat$IntConds)+n] <- 
#       mean(rbeta(100000,c_s[((i-1)*dat$IntConds)+n] + model.alpha,
#                  model.alpha))
#     
  } 

```

Here is the plotting code:

```{r fig.width=7, fig.height=6}
## Create empty data frame
ms <- as.data.frame(matrix(ncol = 1, nrow = 3))

#ms$simple_dm.preds <- c(p_s,p_o,p_w)
#ms$sigma_dm.preds <- c(p_s,p_o,p_w)

ms$mem_dm.preds <- c(p_s,p_o,p_w)

quartz(width=10,height=4.5,title = "Two Process Model Fit")
q <- ggplot(ms, aes(x=intervalN, y=correct, colour=trialType)) +
  facet_grid( ~ numPic) +
  geom_pointrange(aes(ymin = correct-cih,
                      ymax = correct+cih),
                  size = .8) +
  geom_hline(aes(yintercept=1/as.numeric(word(numPic))),lty=2)  +
  #geom_line(aes(y=correct,colour=trialType),data=newdat, lty=1) +
  scale_y_continuous(limits = c(0,1),breaks=c(0,.25,.5,.75,1),
                     name = "Prop. Choosing Repeated Referent") +
  scale_x_continuous(limits=c(.9,10.3), breaks=c(1, 2, 4, 8),
                     name = "Intervening Words") + 
  theme_bw(base_size=18) + 
  scale_color_manual(values=c("dark gray","#808080","#333333","#626262" )) +
  geom_line(aes(group=trialType,y=mem_dm.preds,colour="dark gray"),lty=1,size=1.5) 
# scale_color_grey(start=.2,end=.5)


#scale_color_manual(values=c("dark gray","#619CFF","#F8766D","#00BA38")) +
direct.label(q,list("last.qp",cex=1,hjust=-.15))


```

